language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - ~/.m2

install: true
script: mvn -q -B --global-toolchains travis-maven-toolchain.xml clean install -DskipTests
before_cache:
  - rm -r ~/.m2/repository/org/eclipse/birt
  - rm -r ~/.m2/repository/.cache/tycho
