language: java
jdk:
 - oraclejdk8
   before_deploy:
     # Set up git user name and tag this commit
     - git config --local user.name $GIT_USERNAME
     - git config --local user.email $GIT_EMAIL
     - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
     - git tag $TRAVIS_TAG
   deploy:
     provider: releases
     api_key: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
     file: $FINAL_FILE
     skip_cleanup: true
