language: java
jdk:
 - oraclejdk8
  deploy:
  provider: releases
  api_key: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  file: $FINAL_FILE
  skip_cleanup: true
  on:
    tags: true
